
import { MutualFund, NewsItem } from './types';

export const mutualFundsData: MutualFund[] = [
  {
    vro: 1,
    logoUrl: 'https://picsum.photos/seed/icici/40/40',
    name: 'ICICI Prudential Bluechip Fund',
    category: 'Equity, Large-cap',
    fundSize: '₹44,425',
    returnPa: '+ 21.23%',
    expenseRatio: '1.01%',
    exitLoad: '1.0%',
    age: '10 yrs 11 m',
    sinceDate: 'Since Jan 01, 2013',
    calcReturn: '₹44,425',
  },
  {
    vro: 2,
    logoUrl: 'https://picsum.photos/seed/nippon/40/40',
    name: 'Nippon India Large Cap Fund',
    category: 'Equity, Large-cap',
    fundSize: '₹44,425',
    returnPa: '+ 21.23%',
    expenseRatio: '1.01%',
    exitLoad: '1.0%',
    age: '10 yrs 11 m',
    sinceDate: 'Since Jan 01, 2013',
    calcReturn: '₹44,425',
  },
  {
    vro: 3,
    logoUrl: 'https://picsum.photos/seed/edelweiss/40/40',
    name: 'Edelweiss Large Cap Fund',
    category: 'Equity, Large-cap',
    fundSize: '₹44,425',
    returnPa: '+ 21.23%',
    expenseRatio: '1.01%',
    exitLoad: '1.0%',
    age: '10 yrs 11 m',
    sinceDate: 'Since Jan 01, 2013',
    calcReturn: '₹44,425',
  },
  {
    vro: 4,
    logoUrl: 'https://picsum.photos/seed/kotak/40/40',
    name: 'Kotak Bluechip Fund',
    category: 'Equity, Large-cap',
    fundSize: '₹44,425',
    returnPa: '+ 21.23%',
    expenseRatio: '1.01%',
    exitLoad: '1.0%',
    age: '10 yrs 11 m',
    sinceDate: 'Since Jan 01, 2013',
    calcReturn: '₹44,425',
  },
  {
    vro: 5,
    logoUrl: 'https://picsum.photos/seed/icici2/40/40',
    name: 'ICICI Prudential Bluechip Fund',
    category: 'Equity, Large-cap',
    fundSize: '₹44,425',
    returnPa: '+ 21.23%',
    expenseRatio: '1.01%',
    exitLoad: '1.0%',
    age: '10 yrs 11 m',
    sinceDate: 'Since Jan 01, 2013',
    calcReturn: '₹44,425',
  },
  {
    vro: 6,
    logoUrl: 'https://picsum.photos/seed/icici3/40/40',
    name: 'ICICI Prudential Bluechip Fund',
    category: 'Equity, Large-cap',
    fundSize: '₹44,425',
    returnPa: '+ 21.23%',
    expenseRatio: '1.01%',
    exitLoad: '1.0%',
    age: '10 yrs 11 m',
    sinceDate: 'Since Jan 01, 2013',
    calcReturn: '₹44,425',
  },
  {
    vro: 7,
    logoUrl: 'https://picsum.photos/seed/icici4/40/40',
    name: 'ICICI Prudential Bluechip Fund',
    category: 'Equity, Large-cap',
    fundSize: '₹44,425',
    returnPa: '+ 21.23%',
    expenseRatio: '1.01%',
    exitLoad: '1.0%',
    age: '10 yrs 11 m',
    sinceDate: 'Since Jan 01, 2013',
    calcReturn: '₹44,425',
  },
  {
    vro: 8,
    logoUrl: 'https://picsum.photos/seed/icici5/40/40',
    name: 'ICICI Prudential Bluechip Fund',
    category: 'Equity, Large-cap',
    fundSize: '₹44,425',
    returnPa: '+ 21.23%',
    expenseRatio: '1.01%',
    exitLoad: '1.0%',
    age: '10 yrs 11 m',
    sinceDate: 'Since Jan 01, 2013',
    calcReturn: '₹44,425',
  },
  {
    vro: 9,
    logoUrl: 'https://picsum.photos/seed/icici6/40/40',
    name: 'ICICI Prudential Bluechip Fund',
    category: 'Equity, Large-cap',
    fundSize: '₹44,425',
    returnPa: '+ 21.23%',
    expenseRatio: '1.01%',
    exitLoad: '1.0%',
    age: '10 yrs 11 m',
    sinceDate: 'Since Jan 01, 2013',
    calcReturn: '₹44,425',
  },
  {
    vro: 10,
    logoUrl: 'https://picsum.photos/seed/icici7/40/40',
    name: 'ICICI Prudential Bluechip Fund',
    category: 'Equity, Large-cap',
    fundSize: '₹44,425',
    returnPa: '+ 21.23%',
    expenseRatio: '1.01%',
    exitLoad: '1.0%',
    age: '10 yrs 11 m',
    sinceDate: 'Since Jan 01, 2013',
    calcReturn: '₹44,425',
  },
];

export const newsData: NewsItem[] = [
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
];
