import { MutualFund, NewsItem } from './types';

export const mutualFundsData: MutualFund[] = [
  {
    schemeCode: 120503,
    vro: 1,
    logoUrl: 'https://picsum.photos/seed/icici/40/40',
    name: 'ICICI Prudential Bluechip Fund',
    category: 'Equity, Large-cap',
    fundSize: 44425,
    returnPa: 21.23,
    expenseRatio: 1.01,
    exitLoad: 1.0,
    age: '10 yrs 11 m',
    sinceDate: 'Since Jan 01, 2013',
    calcReturn: 44425,
    risk: 'High',
    duration: '3 Years',
    returns: 'Annualized',
    method: 'Lumpsum',
    payout: 'Direct',
  },
  {
    schemeCode: 119598,
    vro: 2,
    logoUrl: 'https://picsum.photos/seed/nippon/40/40',
    name: 'Nippon India Large Cap Fund',
    category: 'Equity, Large-cap',
    fundSize: 35210,
    returnPa: 19.85,
    expenseRatio: 1.1,
    exitLoad: 1.0,
    age: '11 yrs 2 m',
    sinceDate: 'Since Nov 22, 2012',
    calcReturn: 35210,
    risk: 'High',
    duration: '5 Years',
    returns: 'Annualized',
    method: 'Monthly SIP',
    payout: 'Regular',
  },
  {
    schemeCode: 120473,
    vro: 3,
    logoUrl: 'https://picsum.photos/seed/edelweiss/40/40',
    name: 'Edelweiss Large Cap Fund',
    category: 'Equity, Large-cap',
    fundSize: 21050,
    returnPa: 15.6,
    expenseRatio: 0.95,
    exitLoad: 1.0,
    age: '8 yrs 5 m',
    sinceDate: 'Since Aug 14, 2015',
    calcReturn: 21050,
    risk: 'Moderate',
    duration: '1 Year',
    returns: 'Absolute',
    method: 'Lumpsum',
    payout: 'Direct',
  },
  {
    schemeCode: 120461,
    vro: 4,
    logoUrl: 'https://picsum.photos/seed/kotak/40/40',
    name: 'Kotak Bluechip Fund',
    category: 'Equity, Large-cap',
    fundSize: 52100,
    returnPa: 22.5,
    expenseRatio: 0.89,
    exitLoad: 1.0,
    age: '12 yrs 1 m',
    sinceDate: 'Since Dec 05, 2011',
    calcReturn: 52100,
    risk: 'High',
    duration: '5 Years',
    returns: 'Annualized',
    method: 'Monthly SIP',
    payout: 'Direct',
  },
  {
    schemeCode: 118663,
    vro: 5,
    logoUrl: 'https://picsum.photos/seed/mirae/40/40',
    name: 'Mirae Asset Large Cap Fund',
    category: 'Equity, Large-cap',
    fundSize: 37800,
    returnPa: 20.1,
    expenseRatio: 0.92,
    exitLoad: 0.5,
    age: '9 yrs 8 m',
    sinceDate: 'Since May 01, 2014',
    calcReturn: 37800,
    risk: 'Moderate',
    duration: '3 Years',
    returns: 'Annualized',
    method: 'Lumpsum',
    payout: 'Regular',
  },
  {
    schemeCode: 120468,
    vro: 6,
    logoUrl: 'https://picsum.photos/seed/axis/40/40',
    name: 'Axis Bluechip Fund',
    category: 'Equity, Large-cap',
    fundSize: 33450,
    returnPa: 18.7,
    expenseRatio: 1.05,
    exitLoad: 1.0,
    age: '10 yrs 2 m',
    sinceDate: 'Since Nov 11, 2013',
    calcReturn: 33450,
    risk: 'Moderate',
    duration: '3 Years',
    returns: 'Annualized',
    method: 'Monthly SIP',
    payout: 'Direct',
  },
  {
    schemeCode: 100035,
    vro: 7,
    logoUrl: 'https://picsum.photos/seed/uti/40/40',
    name: 'UTI Mastershare Unit Scheme',
    category: 'Equity, Large-cap',
    fundSize: 15600,
    returnPa: 14.2,
    expenseRatio: 1.2,
    exitLoad: 0.0,
    age: '15 yrs 0 m',
    sinceDate: 'Since Jan 01, 2009',
    calcReturn: 15600,
    risk: 'Low',
    duration: '1 Month',
    returns: 'Absolute',
    method: 'Lumpsum',
    payout: 'Regular',
  },
  {
    schemeCode: 119565, // Replaced Franklin India Bluechip
    vro: 8,
    logoUrl: 'https://picsum.photos/seed/canara/40/40',
    name: 'Canara Robeco Bluechip Equity Fund',
    category: 'Equity, Large-cap',
    fundSize: 12500,
    returnPa: 17.5,
    expenseRatio: 0.9,
    exitLoad: 1.0,
    age: '11 yrs 5 m',
    sinceDate: 'Since Aug 20, 2012',
    calcReturn: 12500,
    risk: 'Moderate',
    duration: '6 Months',
    returns: 'Absolute',
    method: 'Monthly SIP',
    payout: 'Direct',
  },
  {
    schemeCode: 119594,
    vro: 9,
    logoUrl: 'https://picsum.photos/seed/sbi/40/40',
    name: 'SBI Bluechip Fund',
    category: 'Equity, Large-cap',
    fundSize: 41200,
    returnPa: 20.5,
    expenseRatio: 0.98,
    exitLoad: 1.0,
    age: '11 yrs 9 m',
    sinceDate: 'Since Apr 15, 2012',
    calcReturn: 41200,
    risk: 'High',
    duration: '5 Years',
    returns: 'Annualized',
    method: 'Lumpsum',
    payout: 'Direct',
  },
  {
    schemeCode: 105634,
    vro: 10,
    logoUrl: 'https://picsum.photos/seed/hdfc/40/40',
    name: 'HDFC Top 100 Fund',
    category: 'Equity, Large-cap',
    fundSize: 28900,
    returnPa: 17.8,
    expenseRatio: 1.08,
    exitLoad: 1.0,
    age: '14 yrs 6 m',
    sinceDate: 'Since Jul 01, 2009',
    calcReturn: 28900,
    risk: 'Low',
    duration: '3 Months',
    returns: 'Absolute',
    method: 'Monthly SIP',
    payout: 'Regular',
  },
];


export const newsData: NewsItem[] = [
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
  { title: 'Reliance set to release their Q3 reports', date: 'on 21/03/2024' },
];
